### ISSUE TITLE
exago build failure with gcc940 

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#231]
xr_l_g94-xsdk-100-linux-gcc940 

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299110

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/12885083/spack-build-out.txt)

**Comment by balay** [comment]
Another error with  `xr_l_g113-xsdk-100-linux-gcc1131`

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299064

Note: you can access the build log by `browsing` the `artifacts` section on the above URL

**Comment by balay** [comment]
`xr_l_g113-xsdk-cuda-100-linux-gcc1131 `

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299076

**Comment by balay** [comment]
` xr_l_g132-xsdk-100-linux-gcc1321` 

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299104

**Comment by balay** [comment]
xr_l_i23-xsdk-100-linux-oneapi2023-2-0

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299105

Log in the artifacts above

**Comment by balay** [comment]
xr_l_i23-xsdk-100-linux-oneapi2023-1-0

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299092

Log in the artifacts above

**Comment by balay** [comment]
xr_l_i22-xsdk-100-linux-oneapi202220 

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299111

Log in the artifacts above

**Comment by cameronrutherford** [comment]
Going to compile a list and make sure relevant issues are linked:

- [x] [`xr_l_g94-xsdk-100-linux-gcc940`](https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299110) is the same as #226 
- [x] [`xr_l_g113-xsdk-100-linux-gcc1131`](https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299064) is the same as #226 
- [x] [`xr_l_g113-xsdk-cuda-100-linux-gcc1131`](https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299076) is the same as #226 
- [x] [`xr_l_g132-xsdk-100-linux-gcc1321`](https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299104) is the same as #226

Visually verified the rest are all the same. Should be able to spin up a CPU GitHub action pipeline too catch these all preventatively in the future. We are doing a code freeze and will prioritise any remaining build issues in xSDK moving forward.

Note we have build issues with python without MPI https://github.com/pnnl/ExaGO/issues/16, as well as without python and without MPI https://github.com/pnnl/ExaGO/issues/39, so these are at least two examples of things we need to fixup before release, but we are basically there.

See as well the milestone and remaining issues for our release https://github.com/pnnl/ExaGO/milestone/1

**Comment by balay** [comment]
Thanks! The latest pipeline has successful exago builds.

https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/1036334714

**Comment by cameronrutherford** [comment]
https://github.com/pnnl/ExaGO/pull/41 - closes this
